castai-evictor:
  managedByCASTAI: true
  apiKeySecretRef: "castai-cluster-secret"
  provider: "eks"
  clusterIdSecretKeyRef:
    name: "castai-cluster-secret"
    key: "CLUSTER_ID"
  managedByCASTAI: false
  nodeGracePeriodMinutes: 10