apiVersion: helm.config.gke.io/v1
kind: HelmChart
metadata:
  name: castai-workload-autoscaler
  namespace: config-management-system  # Helm controller's record lives here
spec:
  chart: castai-workload-autoscaler
  repo: https://castai.github.io/helm-charts
  version: 0.1.111  # Set your preferred chart version
  releaseName: castai-workload-autoscaler
  targetNamespace: castai-agent       # All resources go here
  values:
    castai:
      apiKeySecretRef: "castai-cluster-controller"
      configMapRef: "castai-cluster-controller"
    test:
      enabled: false