apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: castai-workload-autoscaler
    repo: https://castai.github.io/helm-charts
    version: 0.1.111
    releaseName: castai-workload-autoscaler
    namespace: castai-agent
    valuesInline:
      castai:
        apiKeySecretRef: "castai-cluster-controller"
        configMapRef: "castai-cluster-controller"
      test:
        enabled: false
