apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: castai-workload-autoscaler
  namespace: config-management-system
spec:
  sourceType: helm
  helm:
    repo: https://castai.github.io/helm-charts
    chart: castai-workload-autoscaler
    version: 0.1.111
    releaseName: castai-workload-autoscaler
    namespace: castai-agent  # This is where Helm will install the resources
    values:
      castai:
        apiKeySecretRef: "castai-cluster-controller"
        configMapRef: "castai-cluster-controller"
      test:
        enabled: false
