
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster-project
  namespace: argocd
spec:
  description: In-cluster components
  sourceRepos:  ["*"]
  destinations:
  - server: "*"
    namespace: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
